Upgrade alleyinteractive/wp-type-extensions to support 3.0, add matrix for testing split versions

diff --git a/.github/workflows/all-pr-tests.yml b/.github/workflows/all-pr-tests.yml
--- a/.github/workflows/all-pr-tests.yml
+++ b/.github/workflows/all-pr-tests.yml
@@ -16,6 +16,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        dependencies: ["lowest", "highest"]
         php: [8.1, 8.2, 8.3]
         wordpress: ["latest"]
         multisite: [false, true]
@@ -37,9 +38,30 @@ jobs:
         # See https://github.com/alleyinteractive/action-test-php for more options
         uses: alleyinteractive/action-test-php@develop
         with:
+          install-command: ${{ matrix.dependencies == 'lowest' && 'composer update --prefer-lowest --no-interaction --no-progress' || 'composer install --prefer-dist --no-interaction --no-progress' }}
           php-version: '${{ matrix.php }}'
           skip-audit: 'true'
-          wordpress-version: '${{ matrix.wordpress }}'
-          wordpress-multisite: '${{ matrix.multisite }}'
           skip-core-test-suite: 'true'
           skip-wordpress-install: 'true'
+          wordpress-multisite: '${{ matrix.multisite }}'
+          wordpress-version: '${{ matrix.wordpress }}'
+  # This required job ensures that all PR checks have passed before merging.
+  all-pr-checks-passed:
+    name: All PR checks passed
+    needs:
+      - pr-tests
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check job statuses
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
+            echo "One or more jobs failed"
+            exit 1
+          elif [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more jobs were cancelled"
+            exit 1
+          else
+            echo "All jobs passed or were skipped"
+            exit 0
+          fi
